In [2]:
import numpy as np

#### __1.__ Решите систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

In [26]:
A = np.array([[1, -2], [3, -4]])
np.linalg.det(A).round(3)

2.0

𝑑𝑒𝑡𝐴=≠0, следовательно, система совместна.

In [27]:
b = np.array([1, 7])

for i in np.arange(A.shape[1]):
    A_i = A.copy()
    A_i[:, i] = b
    x_i = np.linalg.det(A_i) / np.linalg.det(A)
    print(f'x{i +1} = {x_i.round(3)}')

x1 = 5.0
x2 = 2.0


   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [29]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
np.linalg.det(A).round(3)

43.0

𝑑𝑒𝑡𝐴=≠0, следовательно, система совместна.

In [30]:
b = np.array([10, -2, 1])

for i in np.arange(A.shape[1]):
    A_i = A.copy()
    A_i[:, i] = b
    x_i = np.linalg.det(A_i) / np.linalg.det(A)
    print(f'x{i +1} = {x_i.round(3)}')

x1 = 2.0
x2 = -1.0
x3 = 1.0


#### __2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а) $\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$
    
   

 Шаг 1  
   U $\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l32 & 1
\end{pmatrix}$
    

 Шаг 2  
   U $\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$
    

б) $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$

 Шаг 1  
   U $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 5\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 27
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l32 & 1 & 0\\
4 & l42 & l43 & 1
\end{pmatrix}$
    

 Шаг 2  
   U $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 5\\ 
0 & 0 & 3 & -19\\
0 & 0 & 21 & -3
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l43 & 1
\end{pmatrix}$

 Шаг 2  
   U $\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 5\\ 
0 & 0 & 3 & -19\\
0 & 0 & 0 & 130
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

#### __3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

Найдем L и U матрицы:

 Шаг 1  
   U $\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 3.5 & -9.5
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & l23 & 1
\end{pmatrix}$
    

 Шаг 2  
   U $\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5 \\ 
0 & 0 & 52/3
\end{pmatrix}$  L $\begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & 7/3 & 1
\end{pmatrix}$
    

$\begin{cases}
y1 = 1 \\
y2 = -6 - 11/2 = -23/2 \\
y3 = -5 - 9/2 + 23*7/6  = 52/3 \\
\end{cases}$

$\begin{cases}
x1 = (1 - 3) = -1 \\
x2 = (-23/2 + 23/2)/(3/2) = 0 \\
x3 = 1 \\
\end{cases}$

Проверка методом Крамера

In [89]:
def kramer(A, b):
    x = np.zeros(b.shape)
    try:
        for i in np.arange(A.shape[1]):
            A_i = A.copy()
            A_i[:, i] = b
            x[i] = np.linalg.det(A_i) / np.linalg.det(A)
            print(f'x{i +1} = {x[i].round(3)}')
    except ZeroDivisionError:
        print('Система является неопределенной.')
        return
    return x

In [93]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

kramer(A, b)

x1 = -1.0
x2 = 0.0
x3 = 1.0


array([-1.00000000e+00,  2.42618668e-16,  1.00000000e+00])

#### __4*.__ Решите систему линейных уравнений методом Холецкого:

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

In [94]:
def is_sim(A):
    if A.shape[0] == A.shape[1]:
        for i in np.arange(A.shape[0]):
            for j in np.arange(A.shape[0]):
                if A[i, j] != A[j, i]:
                    print('Некорректные данные. Матрица коэффициентов должна быть симметричной.')
                    return False        
    else:
        print('Некорректные данные. Матрица коэффициентов должна быть квадратной.')
        return False
    return True

In [95]:
def holezky(A, b):
    if not is_sim(A):
        return
    l = np.zeros(A.shape)
    for j in np.arange(A.shape[0]):
        for i in np.arange(A.shape[0]):
            if i == j:
                l[i, j] = np.sqrt(A[i, i] - np.sum([l[i, k] ** 2 for k in np.arange(i)]))
            elif i > j:
                l[i, j] = (A[i, j] - np.sum([l[i, k] * l[j, k] for k in np.arange(i)])) / l[j, j]
    y = np.zeros(b.shape)   
    for i in np.arange(A.shape[0]):
        y[i] = (b[i] - np.sum([l[i, j] * y[j] for j in np.arange(i)])) / l[i, i]
    
    x = np.zeros(b.shape)
    for i in np.arange(A.shape[0] - 1, -1, -1):
        x[i] = (y[i] - np.sum([l.T[i, j] * x[j] for j in np.arange(i + 1, A.shape[0])])) / l.T[i, i]
        print(f'x{i+1} = {x[i].round(5)}')
    return x

In [96]:
# Проверка на данных из методички

A = np.array([[2, 1, 4], [1, 1, 3], [4, 3, 14]])
b = np.array([16, 12, 52])

holezky(A, b)

x3 = 3.0
x2 = 2.0
x1 = 1.0


array([1., 2., 3.])

In [97]:
A = np.array([[81, -45, 45],[-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

holezky(A, b)

x3 = -4.0
x2 = -5.0
x1 = 6.0


array([ 6., -5., -4.])