1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np

In [9]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

U, d, V_T = np.linalg.svd(A)
D = np.zeros_like(A,dtype='float')
np.fill_diagonal(D, d)
print(f'Матрица U ({U.shape[0]}x{U.shape[1]}): ', U, sep='\n', end='\n\n')
print(f'Матрица D ({D.shape[0]}x{D.shape[1]}): ', D, sep='\n', end='\n\n')
print(f'Матрица V_T ({V_T.shape[0]}x{V_T.shape[1]}): ', V_T, sep='\n', end='\n\n')

Матрица U (5x5): 
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]

Матрица D (5x3): 
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Матрица V_T (3x3): 
[[ 0.07116451  0.71702467  0.69340553]
 [-0.36737824  0.66514082 -0.65009301]
 [-0.92734505 -0.20847855  0.31075368]]



2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;

In [16]:
A_Enorm = d[0]
A_Enorm, np.linalg.norm(A, ord=2)

(8.824868854820442, 8.824868854820444)

    б) норму Фробениуса.

In [17]:
A_Fnorm = np.sqrt(np.sum(np.square(d)))
A_Fnorm, np.linalg.norm(A, ord='fro')

(11.045361017187261, 11.045361017187261)